CREATE TABLE `leave_submissions` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(128) NOT NULL DEFAULT '',
  `leave_type` varchar(128) NOT NULL DEFAULT '',
  `leave_period_type` varchar(128) NOT NULL DEFAULT '',
  `copy_email_list` text,
  `notify_everyone` tinyint(1) NOT NULL,
  `submit_note` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `cancel_note` text,
  `created_date` datetime NOT NULL,
  `updated_date` datetime DEFAULT NULL,
  `email_id` text NOT NULL,
  `email_subject` text,
  `active` tinyint(1) DEFAULT NULL,
  `start_date` datetime NOT NULL,
  `end_date` datetime NOT NULL,
  `start_half` tinyint(1) DEFAULT NULL,
  `end_half` tinyint(1) DEFAULT NULL,
  `canceled_date` datetime DEFAULT NULL,
  `num_days` double DEFAULT NULL,
  `public_submit_note` tinyint(1) DEFAULT '1',
  `calendar_event_id` varchar(128) DEFAULT NULL,
  `location` varchar(100) DEFAULT NULL,
  `approver_email` varchar(128) DEFAULT NULL,
  `status` enum('APPROVED','PENDING','REJECTED','CANCELLED') DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3232312317 DEFAULT CHARSET=utf8mb3;
