CREATE TABLE `visitor` (
   `email_hash` varchar(255) NOT NULL,
   `email` varchar(255) DEFAULT NULL,
   `first_name` varchar(255) DEFAULT NULL,
   `last_name` varchar(255) DEFAULT NULL,
   `contact_number` varchar(255) DEFAULT NULL,
   `created_by` varchar(255) DEFAULT NULL,
   `created_on` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
   `updated_by` varchar(255) DEFAULT NULL,
   `updated_on` timestamp(6) NULL DEFAULT CURRENT_TIMESTAMP(6),
   PRIMARY KEY (`email_hash`),
   UNIQUE KEY `email_hash_UNIQUE` (`email_hash`),
   UNIQUE KEY `email_UNIQUE` (`email`)
 );

 CREATE TABLE `visit` (
   `visit_id` int NOT NULL AUTO_INCREMENT,
   `uuid` char(36) NOT NULL,
   `email_hash` varchar(255) NOT NULL,
   `pass_number` varchar(50) DEFAULT NULL,
   `company_name` varchar(255) DEFAULT NULL,
   `whom_they_meet` varchar(255) DEFAULT NULL,
   `purpose_of_visit` text,
   `accessible_locations` json DEFAULT NULL,
   `visit_date` char(12) NOT NULL,
   `time_of_entry` datetime DEFAULT NULL,
   `time_of_departure` datetime DEFAULT NULL,
   `invitation_id` int DEFAULT NULL,
   `rejection_reason` varchar(45) DEFAULT NULL,
   `actioned_by` varchar(45) DEFAULT NULL,
   `invited_by` varchar(45) NOT NULL,
   `status` enum('REQUESTED','APPROVED','REJECTED','COMPLETED') NOT NULL,
   `created_by` varchar(60) NOT NULL,
   `created_on` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
   `updated_by` varchar(60) NOT NULL,
   `updated_on` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
   PRIMARY KEY (`visit_id`),
   UNIQUE KEY `uuid_UNIQUE` (`uuid`),
   KEY `fk_invitation_id_idx` (`invitation_id`),
   KEY `email_hash_idx` (`email_hash`),
   CONSTRAINT `email_hash` FOREIGN KEY (`email_hash`) REFERENCES `visitor` (`email_hash`)
 );